{
 "title": "Panorama de vendas de seguros",
 "time": { "from": "now-10d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vendas por UF",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "pessoa.endereco_pessoa.uf.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "dth_compra", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "dth_compra"
    }
   ]
  },
  {
   "title": "Vendas por Marca de Veículo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "pessoa.veiculo.marca.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "dth_compra", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "dth_compra"
    }
   ]
  },
  {
   "title": "Timeline de valor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Valor vendido",
     "bucketAggs": [
      { "field": "dth_compra", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "valor_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "dth_compra"
    }
   ]
  },
  {
   "title": "Timeline de valor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "currencyBRL" }
   ],
   "targets": [
    {
     "alias": "Valor vendido",
     "bucketAggs": [
      { "field": "dth_compra", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "valor_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "dth_compra"
    }
   ]
  },
  {
   "title": "Timeline de valor",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "alias": "Valor vendido",
     "bucketAggs": [
      {
       "fake": true,
       "field": "pessoa.veiculo.tipo.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pessoa.endereco_pessoa.uf.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "dth_compra", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "valor_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "dth_compra"
    }
   ]
  },
  {
   "title": "Timeline de valor",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "num_apolice",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "produto.nome_produto.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pessoa.veiculo.tipo.keyword",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "pessoa.endereco_pessoa.uf.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "num_apolice",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "timeField": "dth_compra"
    }
   ]
  }
 ]
}